myapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views as currency_views

app_name = "myapp"

urlpatterns = [
    path('', currency_views.IndexView.as_view(), name="index"),

    # Book pages
    path('books', currency_views.BookView.as_view(), name="books"),
    path('books/add', currency_views.AddBookView.as_view(), name="add_book"),
    path('books/delete/<int:id>', currency_views.DeleteBookView.as_view(), name="delete_book"),
    path('books/edit/<int:id>', currency_views.AddBookView.as_view(), name="edit_book"),

    # Collection pages
    path('collection', currency_views.CollectionView.as_view(), name="collection"),
    path('collection/add', currency_views.AddEntryView.as_view(), name="add_entry"),
    path('collection/delete/<int:id>', currency_views.DeleteEntryView.as_view(), name="delete_entry"),
    path('collection/edit/<int:id>', currency_views.AddEntryView.as_view(), name="edit_entry"),

    # Authorization pages.
    path('login/', currency_views.LoginView.as_view(), name='login'),
    path('logout/', currency_views.LogoutView.as_view(), name='logout'),
]

myapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class Book(models.Model):
    description = models.CharField(max_length=100)
    pages = models.IntegerField(null=True, default=None)
    rows_per_page = models.IntegerField(null=True, default=None)
    columns_per_row = models.IntegerField(null=True, default=None)

    # Audit Fields.
    created_ts = models.DateTimeField(auto_now_add=True)
    updated_ts = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description


class Currency(models.Model):
    Bill = "Bill"
    Coin = "Coin"

    TYPE_CHOICES = [
        (Bill, "Bill"),
        (Coin, "Coin")
    ]

    book = models.ForeignKey(Book, on_delete=CASCADE)
    page = models.IntegerField(null=True, default=None)
    row = models.IntegerField(null=True, default=None)
    column = models.IntegerField(null=True, default=None)
    currency = models.CharField(max_length=100, blank=True, default="")
    value = models.DecimalField(max_digits=19, decimal_places=2, null=True, default=None)
    type = models.CharField(max_length=4, choices=TYPE_CHOICES)
    country = models.CharField(max_length=2, blank=True, default="")

    # Audit Fields.
    created_ts = models.DateTimeField(auto_now_add=True)
    updated_ts = models.DateTimeField(auto_now=True)

myapp/forms.py
import pycountry

from django import forms

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UsernameField

from myapp import models


class BookForm(forms.ModelForm):
    rows_per_page = forms.IntegerField(label="Rows Per Page", required=False, min_value=0)
    columns_per_row = forms.IntegerField(label="Columns Per Row", required=False, min_value=0)
    pages = forms.IntegerField(required=False, min_value=0)

    class Meta:
        model = models.Book
        exclude = ["id", "created_ts", "updated_ts"]


class EntryForm(forms.ModelForm):
    book = forms.ModelChoiceField(models.Book.objects.all(), required=True,
                                  to_field_name='description')

    def __init__(self, *args, **kwargs):
        countries = [(country.alpha_2, country.name) for country in pycountry.countries]

        countries.insert(0, ("", "-" * 9))

        historic = [(country.alpha_2, country.name) for country in pycountry.historic_countries if
                    not country.name == "Serbia and Montenegro"]

        countries.extend(historic)

        # These are non-iso coded countries.
        custom_countries = [
            ("AA", "Central Africa CFA"),
            ("CE", "Eastern Carribean Islands"),
            ("MB", "Serbia and Montenegro"),
            ("WA", "West Africa CFA")
        ]

        countries.extend(custom_countries)

        countries.sort()

        super().__init__(*args, **kwargs)
        self.fields["country"] = forms.ChoiceField(choices=countries, required=False)

    class Meta:
        model = models.Currency
        exclude = ["id", "created_ts", "updated_ts"]


class LoginForm(AuthenticationForm):
    username = UsernameField(max_length=254, widget=forms.TextInput())

myapp/views.py
import json
import pycountry

from django.contrib import messages
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView
from django.views.generic import RedirectView

from myapp import forms
from myapp import utils
from myapp.decorators import write_perms_required
from myapp.models import Book
from myapp.models import Currency

from pycountry import countries
from pycountry import historic_countries


@method_decorator(write_perms_required, name="dispatch")
class AddBookView(LoginRequiredMixin, View):
    t = "add_book.html"

    def get_book_info(self, id):
        """Attempt to get book based on ID specified. If there was an error, this will return None.
        """
        try:
            results = Book.objects.get(pk=id)
        except Book.DoesNotExist:
            return None

        return results

    def get(self, request, id=None):
        ctx = {}

        # If editing an existing entry.
        if id:
            book = self.get_book_info(id)

            if not book:
                messages.error(request, "Invalid book specified.")
                return redirect("myapp:books")

            ctx["form"] = forms.BookForm(instance=book)
            ctx["book"] = book

        else:
            ctx["form"] = forms.BookForm()

        return render(request, self.t, ctx)

    def post(self, request, id=None):
        ctx = {}

        # If editing an existing book
        if id:
            book = self.get_book_info(id)
            ctx["book"] = book

            if not book:
                messages.error(request, "Invalid book specified.")
                return redirect("myapp:books")

            form = forms.BookForm(request.POST, instance=book)
        else:
            form = forms.BookForm(request.POST)

        if not form.is_valid():
            messages.error(request, "Form is invalid, make appropriate corrections and try again.")
            ctx["form"] = form
            return render(request, self.t, ctx)

        form.save()

        if id:
            message = "Updated book successfully."
        else:
            message = "Created new book successfully."

        messages.success(request, message)

        # Redirect to appropriate page based on button clicked.
        if "_create_another" in request.POST:
            return redirect("myapp:add_book")
        else:
            return redirect("myapp:books")


@method_decorator(write_perms_required, name="dispatch")
class AddEntryView(LoginRequiredMixin, View):
    t = "add_entry.html"

    def get_entry_info(self, id):
        """Attempt to get entry based on ID specified. If there was an error, this will return None.
        """
        try:
            results = Currency.objects.get(pk=id)
        except Currency.DoesNotExist:
            return None

        return results

    def get(self, request, id=None):
        ctx = {}

        # If editing an existing entry.
        if id:
            entry = self.get_entry_info(id)

            if not entry:
                messages.error(request, "Invalid entry specified.")
                return redirect("myapp:collection")

            ctx["form"] = forms.EntryForm(instance=entry, initial={"book": entry.book})
            ctx["entry"] = entry

        else:
            ctx["form"] = forms.EntryForm()

        return render(request, self.t, ctx)

    def post(self, request, id=None):
        ctx = {}

        # If editing an existing entry
        if id:
            entry = self.get_entry_info(id)
            ctx["entry"] = entry

            if not entry:
                messages.error(request, "Invalid entry specified.")
                return redirect("myapp:collection")

            form = forms.EntryForm(request.POST, instance=entry)
        else:
            form = forms.EntryForm(request.POST)

        if not form.is_valid():
            messages.error(request, "Form is invalid, make appropriate corrections and try again.")
            ctx["form"] = form
            return render(request, self.t, ctx)

        form.save()

        if id:
            message = "Updated entry successfully."
        else:
            message = "Created new entry successfully."

        messages.success(request, message)

        # Redirect to appropriate page based on button clicked.
        if "_create_another" in request.POST:
            return redirect("myapp:add_entry")
        else:
            return redirect("myapp:collection")


class BookView(LoginRequiredMixin, View):
    t = "books.html"

    def get(self, request):
        ctx = {}

        ctx["books"] = Book.objects.all()

        ctx["read_only_user"] = utils.is_read_only_user(request.user)

        return render(request, self.t, ctx)


class CollectionView(LoginRequiredMixin, View):
    t = "collection.html"

    def get(self, request):
        ctx = {}

        currency = Currency.objects.all()

        results = []

        for line in currency:
            line_info = {}
            line_info["id"] = line.id
            line_info["book"] = line.book
            line_info["page"] = line.page
            line_info["row"] = line.row
            line_info["column"] = line.column
            line_info["currency"] = line.currency
            line_info["value"] = line.value
            line_info["type"] = line.type

            # Hard-coded because CS is used multiple times for different countries.
            if line.country == "CS":
                country_code = "Czechoslovakia"
            elif line.country == "MB":
                country_code == "Serbia and Montenegro"
            elif line.country == "CE":
                # Multiple countries use this as their currency.
                country_code = "Eastern Carribean Islands"
            elif line.country == "WA":
                # Multiple countries use this as their currency.
                country_code = "West Africa CFA"
            elif line.country == "AA":
                # Multiple countries use this as their currency.
                country_code = "Central Africa CFA"
            else:
                try:
                    country_code = countries.get(alpha_2=line.country).name
                except Exception:
                    country_code = None

                if not country_code:
                    try:
                        country_code = historic_countries.get(alpha_2=line.country).name
                    except Exception:
                        country_code = line.country

            line_info["country"] = country_code
            results.append(line_info)

        ctx["results"] = results

        ctx["read_only_user"] = utils.is_read_only_user(request.user)

        return render(request, self.t, ctx)


@method_decorator(write_perms_required, name="dispatch")
class DeleteBookView(LoginRequiredMixin, View):
    def post(self, request, id):
        try:
            Book.objects.get(pk=id).delete()

            messages.success(request, "Successfully deleted book and all it's entries.")

        except Book.DoesNotExist:
            messages.error(request, "Failed to delete book.")

        return redirect("myapp:books")


@method_decorator(write_perms_required, name="dispatch")
class DeleteEntryView(LoginRequiredMixin, View):
    def post(self, request, id):
        try:
            Currency.objects.get(pk=id).delete()

            messages.success(request, "Successfully deleted entry.")

        except Currency.DoesNotExist:
            messages.error(request, "Failed to delete entry.")

        return redirect("myapp:collection")


class IndexView(LoginRequiredMixin, View):
    t = "index.html"

    def get(self, request):
        ctx = {}

        countries = (Currency.objects.filter(type="Coin").distinct()
                             .values_list("country", flat=True))

        country_list = utils.populate_country_list(list(countries))

        ctx["countries"] = json.dumps(country_list)

        countries = [(country.alpha_2, country.name) for country in pycountry.countries]

        # Get a list of countries missing from our collection.
        missing_countries = []

        for line in countries:
            if line[0] not in country_list:
                missing_countries.append(line)

        ctx["missing_countries"] = missing_countries

        return render(request, self.t, ctx)


class LoginView(FormView):
    """Basic login screen.
    """
    success_url = "/"
    form_class = forms.LoginForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'login.html'

    def get_form_kwargs(self):
        """The kwargs passed to the form constructor.

        Inherted from `FormMixin`.
        """
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    @method_decorator(sensitive_post_parameters("password"))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "Incorrect username or password.")
        return super().form_invalid(form)

myapp/templates/add_book.html
{% extends "nav.html" %}
{% load bootstrap4 %}
{% block pageheader %}
    {% if book %}
        <h1 class="h3 mb-4 text-gray-800">Edit Book</h1>
    {% else %}
        <h1 class="h3 mb-4 text-gray-800">Add New Book</h1>
    {% endif %}
{% endblock pageheader %}
{% block content %}
    <div class="row">
        <div class="col-md-5">
            <div class="card card-body">
                {% if book %}
                    <form id="form" action="{% url "myapp:edit_book" book.id %}" method="POST">
                {% else %}
                    <form id="form" action="{% url "myapp:add_book" %}" method="POST">
                {% endif %}
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            {% bootstrap_field form.description %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {% bootstrap_field form.pages %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.rows_per_page %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.columns_per_row %}
                        </div>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'myapp:books' %}" class="btn btn-link">Cancel</a>

                        {% if book %}
                            <button id="btn-submit" type="submit" class="btn btn-primary" title="Submit edits for book.">Submit</button>
                        {% else %}
                            <button name="_create_another" id="btn-submit-2" type="submit" class="btn btn-outline-primary" title="Create new book and create another.">Create Another</button>
                            <button id="btn-submit" type="submit" class="btn btn-primary" title="Create new book and return to book management.">Submit</button>
                        {% endif %}
                    </div>
                </form>
            </div><!--card-->
        </div><!--col-->
    </div><!--row-->
{% endblock content %}
{% block extrajs %}
<script>
    $("document").ready(function() {
        $("#id_description").focus();
    });
</script>
{% endblock extrajs %}

myapp/templates/add_entry.html
{% extends "nav.html" %}
{% load bootstrap4 %}
{% block pageheader %}
    {% if entry %}
        <h1 class="h3 mb-4 text-gray-800">Edit Entry</h1>
    {% else %}
        <h1 class="h3 mb-4 text-gray-800">Add New Entry</h1>
    {% endif %}
{% endblock pageheader %}
{% block content %}
    <div class="row">
        <div class="col-md-5">
            <div class="card card-body">
                {% if entry %}
                    <form id="form" action="{% url "myapp:edit_entry" entry.id %}" method="POST">
                {% else %}
                    <form id="form" action="{% url "myapp:add_entry" %}" method="POST">
                {% endif %}
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            {% bootstrap_field form.book %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {% bootstrap_field form.page %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.row %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.column %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% bootstrap_field form.currency %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {% bootstrap_field form.value %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.type %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            {% bootstrap_field form.country %}
                        </div>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'myapp:collection' %}" class="btn btn-link">Cancel</a>

                        {% if entry %}
                            <button id="btn-submit" type="submit" class="btn btn-primary" title="Submit edits for entry.">Submit</button>
                        {% else %}
                            <button name="_create_another" id="btn-submit-2" type="submit" class="btn btn-outline-primary" title="Create new entry and create another.">Create Another</button>
                            <button id="btn-submit" type="submit" class="btn btn-primary" title="Create new entry and return to collection management.">Submit</button>
                        {% endif %}
                    </div>
                </form>
            </div><!--card-->
        </div><!--col-->
    </div><!--row-->
{% endblock content %}
{% block extrajs %}
<script>
    const test = "{{ entry.book.description }}"

    $("document").ready(function() {
        //Check how many books there are. If there is only one, change focus to page and slot.
        if ($("#id_book").children().length === 1) {
            $("#id_page").focus();
        } else {
            $("#id_book").focus();
        }
    });
</script>
{% endblock extrajs %}

myapp/templates/books.html
{% extends "nav.html" %}
{% block pageheader %}
    <h1 class="h3 mb-4 text-gray-800">Book Management</h1>
{% endblock pageheader %}
{% block content %}

     <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-11">
                    <h6 class="m-0 font-weight-bold text-primary">My Book List</h6>
                </div>
                <div class="col-md-1">
                    {% if read_only_user %}
                        <button class="btn btn-sm btn-primary" disabled title="Disabled, you don't have permission to perform this action.">Add Book</button>
                    {% else %}
                        <a href="{% url "myapp:add_book" %}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top"
                           title="Create a new book.">
                            Add Book
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Pages</th>
                            <th>Rows Per Page</th>
                            <th>Columns Per Row</th>
                            <th width="5%">&nbsp;&nbsp;Edit&nbsp;&nbsp;</th>
                            <th width="5%">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ book.description }}</td>
                                <td>{{ book.pages }}</td>
                                <td>{{ book.rows_per_page }}</td>
                                <td>{{ book.columns_per_row }}</td>
                                <td style="text-align:center" data-toggle="tooltip" data-placement="top" 
                                    {% if read_only_user %}
                                       title="Disabled, you don't have permission to perform this action."
                                    {% else %}
                                        title="Update book information."
                                    {% endif %}
                                >
                                    {% if read_only_user %}
                                        <button class="btn btn-sm btn-light btn-round" disabled><i class="fa fa-pen text-primary"></i></button>
                                    {% else %}
                                        <a href="{% url "myapp:edit_book" book.id %}" class="btn btn-sm btn-light btn-round">
                                            <i class="fa fa-pen text-primary"></i>
                                        </a>
                                    {% endif %}
                                </td>
                                <td style="text-align:center" data-toggle="tooltip" data-placement="top"
                                    {% if read_only_user %}
                                        title="Disabled, you don't have permission to perform this action."
                                    {% endif %}
                                >
                                    {% if read_only_user %}
                                        <button type="submit" class="btn btn-sm btn-light btn-round" disabled>
                                            <i class="fa fa-trash text-danger"></i>
                                        </button>
                                    {% else %}
                                        <form action="{% url "myapp:delete_book" book.id %}" method="POST">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm btn-light btn-round" data-toggle="tooltip" data-placement="top" 
                                                title="Delete this book and all of it's entries."
                                                onclick="return confirm('Are you sure you want to delete this book? This action cannot be undone.')"
                                            >
                                                <i class="fa fa-trash text-danger"></i>
                                            </button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Description</th>
                            <th>Pages</th>
                            <th>Rows Per Page</th>
                            <th>Columns Per Row</th>
                            <th width="5%">&nbsp;&nbsp;Edit&nbsp;&nbsp;</th>
                            <th width="5%">Delete</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
     </div>

{% endblock content %}
{% block extrajs %}
<script>
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>
{% endblock extrajs %}

myapp/templates/collection.html
{% extends "nav.html" %}
{% block pageheader %}
    <h1 class="h3 mb-4 text-gray-800">Collection Management</h1>
{% endblock pageheader %}
{% block content %}

     <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-11">
                    <h6 class="m-0 font-weight-bold text-primary">My Collection</h6>
                </div>
                    {% if read_only_user %}
                        <button class="btn btn-sm btn-primary" disabled title="Disabled, you don't have permission to perform this action.">Add Entry</button>
                    {% else %}
                        <a href="{% url "myapp:add_entry" %}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Create a new collection entry.">
                            Add Entry
                        </a>
                    {% endif %}
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Book</th>
                            <th>Page</th>
                            <th>Row</th>
                            <th>Column</th>
                            <th>Currency</th>
                            <th>Value</th>
                            <th>Type</th>
                            <th>Country Of Origin</th>
                            <th width="5%">&nbsp;&nbsp;Edit&nbsp;&nbsp;</th>
                            <th width="5%">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for line in results %}
                            <tr>
                                <td>{{ line.book }}</td>
                                <td>{{ line.page }}</td>
                                <td>{{ line.row }}</td>
                                <td>{{ line.column }}</td>
                                <td>{{ line.currency }}</td>
                                <td>{{ line.value }}</td>
                                <td>{{ line.type }}</td>
                                <td>{{ line.country }}</td>
                                <td style="text-align:center" data-toggle="tooltip" data-placement="top" 
                                    {% if read_only_user %}
                                       title="Disabled, you don't have permission to perform this action."
                                    {% else %}
                                        title="Update book information."
                                    {% endif %}
                                >
                                    {% if read_only_user %}
                                        <button class="btn btn-sm btn-light btn-round" disabled><i class="fa fa-pen text-primary"></i></button>
                                    {% else %}
                                        <a href="{% url "myapp:edit_entry" line.id %}" class="btn btn-sm btn-light btn-round">
                                            <i class="fa fa-pen text-primary"></i>
                                        </a>
                                    {% endif %}
                                    
                                </td>
                                <td style="text-align:center" data-toggle="tooltip" data-placement="top"
                                    {% if read_only_user %}
                                        title="Disabled, you don't have permission to perform this action."
                                    {% endif %}
                                >
                                    {% if read_only_user %}
                                        <button type="submit" class="btn btn-sm btn-light btn-round" disabled>
                                            <i class="fa fa-trash text-danger"></i>
                                        </button>
                                    {% else %}
                                        <form action="{% url "myapp:delete_entry" line.id %}" method="POST">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm btn-light btn-round" data-toggle="tooltip" data-placement="top" 
                                                title="Delete this collection entry."
                                                onclick="return confirm('Are you sure you want to delete this entry? This action cannot be undone.')"
                                            >
                                                <i class="fa fa-trash text-danger"></i>
                                            </button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Book</th>
                            <th>Page</th>
                            <th>Row</th>
                            <th>Column</th>
                            <th>Currency</th>
                            <th>Value</th>
                            <th>Type</th>
                            <th>Country Of Origin</th>
                            <th width="5%">&nbsp;&nbsp;Edit&nbsp;&nbsp;</th>
                            <th width="5%">Delete</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
     </div>

{% endblock content %}
{% block extrajs %}
<script>
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>
{% endblock extrajs %}